spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db
    username: umutkeremtoren
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# API Configurations
api:
  yahoo-finance:
    base-url: https://query1.finance.yahoo.com/v8/finance/chart
  currency:
    base-url: https://api.freecurrencyapi.com/v1
    api-key: fca_live_dhnE2cewTf09zExDBKPzgxnY40fivhjJTGwax9s8